apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-app-deployment
  namespace: default
  labels:
    app: kotlin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotlin-app
  template:
    metadata:
      labels:
        app: kotlin-app
    spec:
      containers:
        - name: kotlin-app
          #image: gigi7/kotlin-test-native:latest
          image: vaultitem-app-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
