apiVersion: v1
kind: Service
metadata:
  name: kotlin-service
  namespace: default
  labels:
    app: vaultitem-service
spec:
  selector:
    app: vaultitem-service
  ports:
    -   port: 8082
        name: http
        appProtocol: http
        targetPort: 8082

