apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultitem-service-deployment
  namespace: default
  labels:
    app: vaultitem-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultitem-service
  template:
    metadata:
      labels:
        app: vaultitem-service
    spec:
      containers:
        - name: vaultitem-service-container
          image: vaultitem-app-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
