apiVersion: apps/v1
kind: Deployment
metadata:
  name: tirocinio-web-app
  namespace: default
  labels:
    app: tirocinio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tirocinio
  template:
    metadata:
      labels:
        app: tirocinio
    spec:
      containers:
        - name: tirocinio-container
          image: tirocinio-web-app-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: USERS_REST_URL
              value: "http://users-rest:8081/"
            - name: USERS_REST_PORT
              value: "8081"
            - name: FABRIC_REST_URL
              value: "http://host.minikube.internal:8087/api/contract/all"
            - name: FABRIC_REST_PORT
              value: "8087"
          ports:
            - containerPort: 8080
