apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service-deployment
  namespace: default
  labels:
    app: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      hostAliases:
        - ip: 192.168.67.1
          hostnames:
            - "host.minikube.internal"
      containers:
        - name: ui-service-container
          image: ui-service-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULTITEMS_SERVICE_URL
              value: "http://kotlin-service:8082/"
            - name: VAULTITEMS_SERVICE_PORT
              value: "8082"
            - name: USERS_REST_URL
              value: "http://users-rest:8081/"
            - name: USERS_REST_PORT
              value: "8081"
            - name: FABRIC_REST_URL
              value: "https://host.minikube.internal:8447"
            - name: FABRIC_REST_PORT
              value: "8447"
          ports:
            - containerPort: 8080
