apiVersion: v1
kind: Service
metadata:
  name: users-rest
  namespace: default
  labels:
    app: users-service
spec:
  selector:
    app: users-service
  ports:
    -   port: 8081
        name: http
        appProtocol: http
        targetPort: 8081

